source "https://rubygems.org"

# The big 3, MVC, DB and the APP Server
gem "rails", "~> 8.0.0"  # Full-stack web application framework.
gem "pg"                 # Pg is the Ruby interface to the PostgreSQL RDBMS
gem "puma"               # A Ruby/Rack web server built for parallelism.

gem "agent99"                   # An intelligent agent framework for Ruby
gem "ai_client"                 # A generic AI Client for many providers
gem "amazing_print"             # Pretty print Ruby objects with proper indentation and colors
gem "bootsnap", require: false  # Boot large ruby/rails apps faster
gem "debug_me"                  # A tool to print the labeled value of variables.
gem "importmap-rails"           # Use ESM with importmap to manage modern JavaScript in Rails without transpiling or bundling.
gem "jbuilder"                  # Create JSON structures via a Builder-style DSL
gem "kamal", require: false     # Deploy web apps in containers to servers running Docker with zero downtime.
gem "matrix"                    # An implementation of Matrix and Vector classes.
gem "propshaft"                 # Deliver assets for Rails.
gem "raix"                      # Ruby AI eXtensions
gem "solid_cable"               # Database-backed Action Cable backend.
gem "solid_cache"               # A database backed ActiveSupport::Cache::Store
gem "solid_queue"               # Database-backed Active Job backend.
gem "stimulus-rails"            # A modest JavaScript framework for the HTML you already have.
gem "sublayer"                  # A model-agnostic Ruby GenerativeAI DSL and Framework
gem "thruster", require: false  # Zero-config HTTP/2 proxy
gem "turbo-rails"               # The speed of a single-page web application without having to write any JavaScript.
gem "tzinfo-data"               # Timezone Data for TZInfo


group :development, :test do
  gem "brakeman", require: false  # Security vulnerability scanner for Ruby on Rails.
  gem "rubocop-rails-omakase", require: false  # Omakase Ruby styling for Rails
end

group :development do
  gem "web-console"     # A debugging tool for your Ruby on Rails applications.
end

group :test do
  gem "capybara"            # Capybara aims to simplify the process of integration testing Rack applications, such as Rails, Sinatra or Merb
  gem "selenium-webdriver"  # Selenium is a browser automation tool for automated testing of webapps and more
end
