default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smartest_development

test:
  <<: *default
  database: smartest_test

production:
  <<: *default
  database: smartest_production
  username: <%= ENV['SMARTEST_DATABASE_USERNAME'] %>
  password: <%= ENV['SMARTEST_DATABASE_PASSWORD'] %>
